config/routes.rb
Sevendaysports::Application.routes.draw do
  root to: 'static_pages#home', controller: 'static_pages', action: 'home', as: 'root'

  match 'static_pages/contact', to: 'static_pages#contact', as: :contact

  devise_for :users
  # resources :universities
  # resources :events
  resources :articles
  resources :medias
  # resources :teams

  resources :events do
    resources :articles
    resources :medias
  end

  resources :universities do 
    resources :teams 
  end

  resources :teams do
    resources :events
  end

  resources :users do
    resources :medias
  end

  resources :teams do
    resources :medias
  end

  resources :events do
    resources :medias
  end
  
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :author, :home_team_score, :away_team_score, :details, 
                  :event_on, :home_team_id, :away_team_id, :title, 
                  :kind, :winner

  validates_presence_of :author, :home_team_name, :away_team_name, :title, :kind, 
                        :event_on

  has_many :articles, dependent: :destroy
  has_many :medias, as: :mediable

  belongs_to :home_team, class_name: "Team"
  belongs_to :away_team, class_name: "Team"
  belongs_to :user

  scope :by_user, ->(user_id) {where(user_id: user_id).order("name")}
  scope :by_home_team, ->(home_team_id) { where(home_team_id: home_team_id) }
  scope :by_away_team, ->(away_team_id) { where(away_team_id: away_team_id) }
  scope :by_score, -> { select(:home_team_score, :away_team_score, :winner) }
  scope :upcoming, -> { where('event_on >= ?', 1.minute.from_now) }
  scope :past, -> { where('event_on < ?', 1.minute.ago)}
  scope :recent, -> { where('event_on > ?', 3.days.ago) }
  scope :order_desc, -> { order('event_on DESC').limit(3) }
  scope :order_asc, -> { order('event_on ASC') }

  def winner
    if   home_team_score > away_team_score
      home_team_name
    elsif home_team_score == away_team_score
      "#{home_team_name} #{away_team_name}"
    elsif home_team_score < away_team_score
      away_team_name
    else
      'Results not recorded'
    end
  end

  def home_team_name
    home_team.try(:name) || "No home team associated"
  end

  def away_team_name
    away_team.try(:name) || "No away team associated"
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :get_teams, only: [:new, :create, :edit]
  before_filter :get_event, except: [:index, :new, :create]

  def index
    @upcoming_events = Event.upcoming
    @past_events = Event.past
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(params[:event])
    if @event.save
      redirect_to event_path(@event), success: 'Event created!'
    else
      render :new, error: 'There was an error processing your form'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @event.update_attributes(params[:event])
      redirect_to event_path(@event), success: 'Event updated!'
    else
      render :edit, error: 'There was an error updating your form'
    end
  end

  def destroy
    @event.delete
    redirect_to events_path
  end

  private
  def get_event
    @event = Event.find_by_id(params[:id])
  end

  def get_teams
    @teams = Team.all
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def event_on_formatted
    event_on.strftime('%B %d, %Y at: %r')
  end
end

app/views/events/_first_object.html.erb
<div>
	<em>
		<%= link_to 'Create the first Event!', new_event_path, 
				options = { method: :get }  %>
	</em>
</div><!-- END class alert-info -->

app/views/events/_form.html.erb
<div id="main" class="container">
	<div id="content" class="content bg-base section" style="margin-top: -8%;">	
		<div class="ribbon ribbon-highlight">
			<ol class="breadcrumb ribbon-inner">
				<li><%= link_to 'Home', root_path %></li>
				<li><%= link_to 'Universities', events_path %></li>
				<li class="active" title="universities/new"><em>Create an Event</em></li>
			</ol>
		</div><!--/.ribbon.ribbon-highlight-->
		<h3 class="page-title" style="margin-left: 34%;">
			<em style="color: #6699CC">Create</em> an Event
		</h3>
		<%= form_for @event, 
				html: { 
								class: 'form-horizontal',
								role: 'form',
								style: 'margin-left: 35%;'
							} do |f| %>
			<% if @event.errors.any? %>
				<div class="error_messages">
					<h3>Please correct the following errors.</h3>
					<ul>
						<% @event.errors.full_messages.each do |msg| %>
							<li><%= msg %></li>
						<% end %>
					</ul>
				</div>
			<% end %>
			<div class="form-group">
				<%= f.text_field :author, class: 'text_field', 
						placeholder: 'Your name', class: 'form-control input-lg', 
						style: 'width: 50%;' %>
			</div>
			<div class="form-group">
				<%= f.text_field :title, class: 'text_field', 
						placeholder: 'Title of event', class: 'form-control input-lg', 
						style: 'width: 50%;' %>
			</div>
			<div class="form-group">
				<div class="pull-left">
				<%= f.label 'Home Team' %><br />
				<%= f.select :home_team_id, 
						@teams.map { |team| [team.name, team.id] }, 
						class: 'form-control input-lg' %>
				</div>
				<div style="margin-left: 37%;">
				<%= f.label 'Away Team', style: 'margin-left: 6%; margin-top: -1%;' %><br />	
				<%= f.select :away_team_id, 
						@teams.map { |team| [team.name, team.id] } %>
				</div>
			</div>
			<div class="form-group">	
				<%#= f.label 'Away Team' %><br />	
				<%#= f.select :away_team_id, 
						@teams.map { |team| [team.name, team.id] } %>
			</div>
			<div class="form-group">
				<%= f.select :kind, @teams.map { |team| [team.sport_type] }, class: 'form-control input-lg text_field', 
						style: 'width: 50%;' %>
			</div>
			<div class="form-group">
				<%= f.text_field :home_team_score, class: 'text_field', 
						placeholder: 'Home team score', class: 'form-control input-lg', 
						style: 'width: 50%;' %>
			</div>
			<div class="form-group">
				<%= f.text_field :away_team_score, class: 'text_field', 
						placeholder: 'Away team away_team_score', class: 'form-control input-lg', 
						style: 'width: 50%;' %>
			</div>
			
			<div class="form-group">
				<%= f.text_field :winner, class: 'text_field', 
						placeholder: 'Winning team name', class: 'form-control input-lg', 
						style: 'width: 50%;' %>
			</div>
			<div class="form-group">
				<%= f.text_area :details, class: 'text_area', 
						placeholder: 'Details about the event', 
						class: 'form-control input-lg', size: '10x3',
						style: 'width: 50%;' %>
			</div>
			<div class="form-group" style="margin-left: 4.5%;">
				<%= f.datetime_select :event_on, class: 'datetime_select form-control input-lg', 
						style: 'width: 50%;' %>
			</div>
			<div class="form-group" style="margin-left: 12.5%;">
				<%= f.submit 'Create Event!', 
						options = { 
												method: :post, 
												class: 'btn btn-primary' 
											} %>
				<%= link_to :cancel, events_path, class: 'btn btn-small btn-danger' %>
			</div>
		<% end %>	
	</div><!--/#content.content.bg-base.section-->
</div><!--/#main.container-->

app/views/events/edit.html.erb
<div id="main" class="container">
	<div id="content" class="content bg-base section" style="margin-top: -8%;">	
		<div class="ribbon ribbon-highlight">
			<ol class="breadcrumb ribbon-inner">
				<li><%= link_to 'Home', root_path %></li>
				<li><%= link_to 'Events', events_path %></li>
				<li class="active" title="events/new">
						<em>Edit Event</em>
				</li>
			</ol>
		</div><!--/.ribbon.ribbon-highlight-->
		<h6 class="page-title" style="margin-left: 34%;">
			<span style="color: #FF3333"><em>Edit</em></span>
			<small><%= @event.title %></small>
		</h6>
		<%= form_for [@team, @event], 
				html: { 
								class: 'form-horizontal',
								role: 'form',
								style: 'margin-left: 33%;'
							} do |f| %>
			<% if @event.errors.any? %>
				<div class="error_messages">
					<h3>Please correct the following errors.</h3>
					<ul>
						<% @event.errors.full_messages.each do |msg| %>
							<li><%= msg %></li>
						<% end %>
					</ul>
				</div>
			<% end %>
			<div class="form-group">
				<%= f.text_field :author, class: 'text_field', 
						placeholder: 'Your name', class: 'form-control input-lg', 
						style: 'width: 50%;' %>
			</div>
			<div class="form-group">
				<div class="pull-left">
				<%= f.label 'Home Team' %><br />
				<%= f.select :home_team_id, 
						@teams.map { |team| [team.name, team.id] }, 
						class: 'form-control input-lg' %>
				</div>
				<div style="margin-left: 37%;">
				<%= f.label 'Away Team', style: 'margin-left: 6%; margin-top: -1%;' %><br />	
				<%= f.select :away_team_id, 
						@teams.map { |team| [team.name, team.id] } %>
				</div>
			</div>
			<div class="form-group">	
				<%#= f.label 'Away Team' %><br />	
				<%#= f.select :away_team_id, 
						@teams.map { |team| [team.name, team.id] } %>
			</div>
			<div class="form-group">
				<%= f.select :kind, @teams.map { |team| [team.sport_type] }, class: 'form-control input-lg text_field', 
						style: 'width: 50%;' %>
			</div>
			<div class="form-group">
				<%= f.text_field :home_team_score, class: 'text_field', 
						placeholder: 'Home team score', class: 'form-control input-lg', 
						style: 'width: 50%;' %>
			</div>
			<div class="form-group">
				<%= f.text_field :away_team_score, class: 'text_field', 
						placeholder: 'Away team away_team_score', class: 'form-control input-lg', 
						style: 'width: 50%;' %>
			</div>
			
			<div class="form-group">
				<%= f.text_field :winner, class: 'text_field', 
						placeholder: 'Winning team name', class: 'form-control input-lg', 
						style: 'width: 50%;' %>
			</div>
			<div class="form-group">
				<%= f.text_area :details, class: 'text_area', 
						placeholder: 'Details about the event', 
						class: 'form-control input-lg', size: '10x3',
						style: 'width: 50%;' %>
			</div>
			<div class="form-group">
				<%= f.datetime_select :event_on, 
						class: 'datetime_select form-control input-lg' %>
			</div>
			<div class="form-group" style="margin-left: 12.5%;">
				<%= f.submit 'Update Event!', 
					options = { 
											method: :put, 
											class: 'btn btn-lg btn-success' 
										} %>
				<%= link_to :cancel, events_path, class: 'btn btn-sm btn-danger', style: 'margin-top: 2.3%;' %>
			</div>
		<% end %>			
	</div><!--/#content.content.bg-base.section-->
</div><!--/#main.container-->

app/views/events/index.html.erb
<div id="main" class="container">
	<div id="content" class="content bg-base section" style="margin-top: -8%;">	
		<div class="ribbon ribbon-highlight">
			<ol class="breadcrumb ribbon-inner">
				<li><%= link_to 'Home', root_path %></li>

				<li class="active" title="Upcoming & Past Events"><em>Events</em></li>
			</ol>
		</div>
		<% if @upcoming_events.blank? %>
			<h3><small>No Upcoming Events Exist</small></h3>
			<% unless current_user.try(:admin?) %>
				<h5>
					<em>Please contact Adminitrator to approve an event</em>
				</h5>
			<% end %>
			<% if current_user.try(:admin?) %>	
				<%= render 'first_object' %>
			<% end %>
		<% else %>
			<% if current_user.try(:admin?) %>
				<%= button_to 'Create an Event', new_event_path, 
						options = { 
												method: :get, 
												class: 'pull-right btn btn-primary', 
												style: 'margin-bottom: 1%;' 
											} %>
			<% end %>
			<h1 class="entry-title">Upcoming Events</h1>
			<div class="table-responsive">
				<table class="table table-hover table-bordered">
					<thead>
						<th>Title</th>
						<th>Date</th>
						<th>Details</th>
						<th>View</th>
						<% if current_user.try(:admin?) %>
							<th>Edit</th>
							<th>Delete</th>
						<% end %>
					</thead>
					<tbody>
						<% @upcoming_events.each do |upcoming_event| %>
						<tr>
							<td><%= upcoming_event.title %></td>
							<td><%= upcoming_event.event_on.strftime("%a %B %e, %Y") %></td>
							<td><%= upcoming_event.details %></td>
							<td>
								<%= button_to :view, event_path(upcoming_event), 
										options = { 
																method: :get, 
																class: 'btn btn-xs btn-info' 
															} %>
							</td>
							<% if current_user.try(:admin?) %>
								<td>
									<%= button_to :edit, edit_event_path(upcoming_event), 
											options = { 
																	method: :get, 
																	class: 'btn btn-xs btn-default' 
																} %>
								</td>
								<td>
									<%= button_to :delete, event_path(upcoming_event), 
											options = { 
																	method: :delete, 
																	confirm: 'You sure?', 
																	class: 'btn btn-xs btn-danger' 
																} %>
								</td>
							<% end %>
						</tr>
						<% end %>
					</tbody>
				</table>
			</div><!-- END class table-responsive -->
			<% end %>	
			<!-- </div> END class container 
			<div class="container"> -->
<!-- 			<div class="row-fluid">
				<div class="span12">
					<hr />
				</div>
			</div>
		</div>-- /spacer  -->
<!-- 		<div class="container"> -->
			<% if @past_events.blank? %>
				<h3><small>No Past Events Exist</small></h3>
				<%#= render 'first_object' %>
			<% else %>
			<h3 class="entry-title">Past Events</h3>
			<div class="table-responsive">
				<table class="table table-hover table-bordered">
					<thead>
						<th>Title</th>
						<th>Date</th>
						<th>Details</th>
						<th>View</th>
						<% if current_user.try(:admin?) %>
							<th>Edit</th>
							<th>Delete</th>
						<% end %>
					</thead>
					<tbody>
						<% @past_events.each do |past_event| %>
						<tr>
							<td><%= past_event.home_team.name %></td>
							<td><%= past_event.event_on.strftime("%a %B %e, %Y") %></td>
							<td><%= past_event.details %></td>
							<td>
								<%= button_to :view, event_path(past_event), 
										options = { 
																method: :get, 
																class: 'btn btn-xs btn-info' 
															} %>
							</td>
							<% if current_user.try(:admin?) %>
								<td>
									<%= button_to :edit, edit_event_path(past_event), 
											options = { 
																	method: :get, 
																	class: 'btn btn-xs btn-default' 
																} %>
								</td>
								<td>
									<%= button_to :delete, event_path(past_event), 
											options = { 
																	method: :delete, 
																	confirm: 'You sure?', 
																	class: 'btn btn-xs btn-danger' 
																} %>
								</td>
							<% end %>
						</tr>
						<% end %>
					</tbody>
				</table>
			</div><!-- END class table-responsive -->
			<br />
			<%= button_to :back, root_path, class: 'btn btn-sm' %>
		</div><!-- END class container -->
		<% end %>

app/views/events/show.html.erb
<div id="main" class="container">
	<div id="content" class="content bg-base section" style="margin-top: -8;">
		<div class="ribbon ribbon-highlight">
			<ol class="breadcrumb ribbon-inner">
				<li><%= link_to 'Home', root_path %></li>
				<li><%= link_to 'Events', events_path %></li>
				<li class="active" title="Specific Event Page">
					<em><%= @event.home_team_name %></em>
					&nbsp;&nbsp;vs.&nbsp;&nbsp;
					<em><%= @event.away_team_name %></em>
					&nbsp;&nbsp;&nbsp;&nbsp;Date:&nbsp;&nbsp;
					<em><%= @event.event_on.strftime('%m-%d-%y') %></em>
				</li>
			</ol>
		</div>
		<header class="page-header">
			<h1 class="page-title">
				<%= @event.home_team_name %> 
				<small>vs.</small> 
				<%= @event.away_team_name %>
			</h1>
			<small><b>Date</b>: <%= @event.event_on.strftime('%A %B %d, %Y') %></small>
		</header>
		<!--.table-->
		<h1 id="table"><%= @event.title %></h1>
		<div class="table-responsive">
			<table class="table table-hover table-bordered">
				<thead>
					<tr>
						<th>Home Team</th>
						<th>Away Team</th>
						<th>Sport Type</th>
						<th>Date</th>
						<th>Home Team Score</th>
						<th>Away Team Score</th>
						<th>Winner</th>
						<th>Details</th>
						<% if current_user.try(:admin?) %>
							<th>Edit</th>
							<th>Delete</th>
						<% end %>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td><%= @event.home_team_name %></td>
						<td><%= @event.away_team_name %></td>
						<td><%= @event.kind %></td>
						<td><%= @event.event_on.strftime('%A %B %d, %Y') %></td>
						<td><%= @event.home_team_score %></td>
						<td><%= @event.away_team_score %></td>
						<td><%= @event.winner %></td>
						<td><%= @event.details %></td>
						<% if current_user.try(:admin?) %>
							<td>
								<%= button_to :edit, edit_team_event_path(@event),
										options = {
																method: :get,
																class: 'btn btn-sm btn-default'
															} %>
							</td>
							<td>
								<%= button_to :delete, event_path(@event),
										options = {
																method: :delete,
																confirm: 'You sure?',
																class: 'btn btn-sm btn-danger'
															} %>
							</td>
						<% end %>
					</tr>
				</tbody>
			</table>
		</div>
		<br />
		<%= button_to :back, events_path, class: 'btn btn-sm', method: :get %>
</div><!-- END CLASS container -->