config/routes.rb
Sevendaysports::Application.routes.draw do
  root to: 'static_pages#home', controller: 'static_pages', action: 'home', as: 'root'

  match 'static_pages/contact', to: 'static_pages#contact', as: :contact

  devise_for :users
  # resources :universities
  # resources :events
  resources :articles
  resources :medias
  # resources :teams

  resources :events do
    resources :articles
    resources :medias
  end

  resources :universities do 
    resources :teams 
  end

  resources :teams do
    resources :events
  end

  resources :users do
    resources :medias
  end

  resources :teams do
    resources :medias
  end

  resources :events do
    resources :medias
  end
  
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/university.rb
  class University < ActiveRecord::Base
  attr_accessible :address, :city, :name, :state, :url, :zip

  has_many :teams, dependent: :destroy

  validates :zip, presence: true, format: { with: /\A\d{5}(-\d+)?\z/ },
            length: { minimum: 5 }
  validates_presence_of :name, :address, :city, :state, :url

  #scope :ordered, -> { University.order(name: 'ASC') }
  # scope :by_teams, ->(university_id) { Team.find_by_university_id(university_id) }
  # scope :team_by_university, ->(team_id) { where(team_id: team_id).order(name: name)}

  def sport_type
    team.sport_type
  end
end

app/controllers/universities_controller.rb
 class UniversitiesController < ApplicationController
  before_filter :get_university, except: [:index, :new, :create]

  def index
    @universities = University.all
  end

  def new
    @university = University.new
  end

  def create
    @university = University.new(params[:university])
    if @university.save
      redirect_to  @university, success: 'University added!'
    else
      render :new, error: 'There was an error processing your University'
    end
  end

  def show
    @teams = @university.teams
  end

  def edit
  end

  def update
    if @university.update_attributes(params[:university])
      redirect_to @university, method: :put, success: 'University updated!'
    else
      render :edit, error: 'There was an error updating your University'
    end
  end

  def destroy
    @university.delete
    redirect_to universities_path, notice: 'You sure?'
  end

  private
  def get_university
    @university = University.find(params[:id])
  end
end

app/helpers/universities_helper.rb
module UniversitiesHelper
end

app/views/universities/_first_object.html.erb
<div>
	<em>
		<%= link_to 'Add the first University!', new_university_path, 
				options = { method: :get } %>
	</em>
</div>

app/views/universities/_form.html.erb
<div id="main" class="container">
	<div id="content" class="content bg-base section" style="margin-top: -8%;">	
		<div class="ribbon ribbon-highlight">
			<ol class="breadcrumb ribbon-inner">
				<li><%= link_to 'Home', root_path %></li>
				<li><%= link_to 'Universities', universities_path %></li>
				<li class="active" title="universities/new"><em>Form</em></li>
			</ol>
		</div><!--/.ribbon.ribbon-highlight-->
			<h3 class="page-title" style="margin-left: 35.5%;">
				<em style="color: #6699CC">Add</em> a University
			</h3>
		  <%= form_for @university, 
		  		html: { 
		  						class: 'form-horizontal', 
		  						role: 'form', 
		  						style: 'margin-left: 33%;' 
		  					} do |f| %>
				<% if @university.errors.any? %>
					<div class="error_messages">
						<h3>Please correct the following errors.</h3>
						<ul>
							<% @university.errors.full_messages.each do |msg| %>
								<li><%= msg %></li>
							<% end %>
						</ul>
					</div>
				<% end %>
				<div class="form-group">
					<%= f.text_field :name, class: 'text_field', 
							placeholder: 'University Name', 
							class: 'form-control input-lg',
							style: 'width: 50%;'
							 %>
				</div>
				<div class="form-group">
					<%= f.text_field :url, class: 'text-field', 
							placeholder: 'University Website', 
							class: 'form-control input-lg',
							style: 'width: 50%;'
							 %>
				</div>
				<div class="form-group">				
					<%= f.text_area :address, 
							placeholder: 'University Address', 
							size: '32x3', 
							class: 'form-control input-lg',
							style: 'width: 50%;'
							 %>
				</div>
				<div class="form-group">
					<%= f.text_field :city, class: 'text-field', 
							placeholder: 'University City', 
							class: 'form-control input-lg',
							style: 'width: 50%;'
							 %>
				</div>
				<div class="form-group">
					<%= f.text_field :state, class: 'text-field', 
							placeholder: 'University State', 
							class: 'form-control input-lg',
							style: 'width: 50%;'
							 %>
				</div>
				<div class="form-group">
					<%= f.text_field :zip, class: 'text-field', 
							placeholder: 'University Zip', 
							class: 'form-control input-lg',
							style: 'width: 50%;'
							 %>
				</div>
				<div class="form-group" style="margin-left: 10%;">
					<%= f.submit 'Create University!',
							options = { 
													method: :post, 
													class: 'btn btn-primary' 
												} %>
				
					<%= link_to :cancel, universities_path,
							options = {
													method: :get,
													class: 'btn btn-sm btn-danger',
													style: 'margin-left: 1.5%; margin-top: .5%;'
												} %>
				<% end %>	
				</div>
			
	</div><!--/#content.content.bg-base.section-->
</div><!--/#main.container-->

app/views/universities/_team_management.html.erb
<div class="row-fluid">
	<h1 class="entry-title">Teams</h1>
	<% if current_user.try(:admin?) %>
		<%= link_to 'Add a Team', new_university_team_path(@university),
															options = {
																					method: :get,
																					class: 'btn btn-primary'
																				} %>
	<% end %>
	<!--Team Management-->
	<div class="table-responsive">
		<table class="table table-hover table-bordered">
			<thead>
				<th>Name</th>
				<th>Sport Type</th>
				<th>View</th>
				<% if current_user.try(:admin?) %>
					<th>Edit</th>
					<th>Delete</th>
				<% end %>
			</thead>
			<% @teams.each_with_index do |team, university| %>
			<tbody>
				<tr>
					<td><%= team.name %></td>
					<td><%= team.sport_type %></td>
					<td>
						<%= link_to 'View Team', 
								university_team_path(university_id: @university.id, id: team),
								options = {
														method: :get,
														class: 'btn btn-sm btn-info'
													} %>
					</td>
					<% if current_user.try(:admin?) %>
						<td>
							<%= link_to 'Edit', 
									edit_university_team_path(university_id: @university.id, id: team),
									options = {
															method: :get,
															class: 'btn btn-sm btn-default'
														} %>
						</td>
						<td>
							<%= link_to 'Delete', 
									university_team_path(university_id: @university.id, id: team),
									options = {
															method: :delete,
															confirm: 'You sure?',
															class: 'btn btn-sm btn-danger'
														} %>
						</td>
					<% end %>
				</tr>
			</tbody>
			<% end %>
		</table>
	</div><!-- END CLASS table-responsive -->
</div><!--/.row-fluid-->

app/views/universities/edit.html.erb
<div id="main" class="container">
	<div id="content" class="content bg-base section" style="margin-top: -8%;">	
		<div class="ribbon ribbon-highlight">
			<ol class="breadcrumb ribbon-inner">
				<li><%= link_to 'Home', root_path %></li>
				<li><%= link_to 'Universities', universities_path %></li>
				<li class="active" title="universities/new"><em>Edit</em></li>
			</ol>
		</div><!--/.ribbon.ribbon-highlight-->
			<h6 class="page-title" style="margin-left: 36%;">
				<span style="color: #FF3333"><em>Edit</em></span> a University
			</h6>
			<%= form_for @university, 
 								html: { 
 												class: 'form-horizontal', 
 												role: 'form', 
 												style: 'margin-left: 33%;' 
 											} do |f| %>
				<% if @university.errors.any? %>
					<div class="error_messages">
						<h3>Please correct the following errors.</h3>
						<ul>
							<% @university.errors.full_messages.each do |msg| %>
								<li><%= msg %></li>
							<% end %>
						</ul>
					</div>
				<% end %>
				<div class="form-group">
					<%= f.text_field :name, class: 'text_field', 
							placeholder: 'University Name', 
							class: 'form-control input-lg',
							style: 'width: 50%;'
							 %>
				</div>
				<div class="form-group">
					<%= f.text_field :url, class: 'text-field', 
							placeholder: 'University Website',
							class: 'form-control input-lg',
							style: 'width: 50%;'
							 %>
				</div>
				<div class="form-group">				
					<%= f.text_area :address, 
							placeholder: 'University Address', 
							size: '32x3', 
							class: 'form-control input-lg',
							style: 'width: 50%;'
							 %>
				</div>
				<div class="form-group">
					<%= f.text_field :city, class: 'text-field', 
							placeholder: 'University City', 
							class: 'form-control input-lg',
							style: 'width: 50%;'
							 %>
				</div>
				<div class="form-group">
					<%= f.text_field :state, class: 'text-field', 
							placeholder: 'University State', 
							class: 'form-control input-lg',
							style: 'width: 50%;'
							 %>
				</div>
				<div class="form-group">
					<%= f.text_field :zip, class: 'text-field', 
							placeholder: 'University Zip', 
							class: 'form-control input-lg',
							style: 'width: 50%;'
							 %>
				</div>
				<%= button_to :update, university_path(@university), 
						options = { method: :put, 
												class: 'btn btn-lg btn-success', 
												style: 'display: inline; margin-left: 16%;'
											} %>

				<% end %>	

					<%= button_to :cancel, universities_path, 
							options = { 
													method: :get, 
													class: 'btn btn-sm btn-danger', 
													style: 'margin-left: 53%; margin-top: -6.8%;'
												} %>
				</div>
	</div><!--/#content.content.bg-base.section-->
</div><!--/#main.container-->

app/views/universities/index.html.erb
<div id="main" class="container">
	<div id="content" class="content bg-base section" style="margin-top: -8%;">	
		<div class="ribbon ribbon-highlight">
			<ol class="breadcrumb ribbon-inner">
				<li><%= link_to 'Home', root_path %></li>
				<li class="active" title="Universities">Universities</li>
			</ol>
		</div>
		<% if @universities.blank? %>
			<h3><small>No Universitites Exist</small></h3>
			<% if user_signed_in? %>
				<h5>
					<em>Please contact Adminitrator to add a university</em>
				</h5>
			<% end %>
		<% end %>
		<% if @universities.blank? && user_signed_in? %>
			<%= render 'universities/first_object' %>
		<% end %>
	<% else %>
		<!--.table-->
		<h1 class="entry-title">Universities</h1>
		<% if current_user.try(:admin?) %>
			<%= button_to 'Create a University', new_university_path, 
					options = { 
											method: :get, 
											class: 'btn btn-primary pull-right', 
											style: 'margin-bottom: 2%;'
										} %>
		<% end %>
		<div class="table-responsive">
			<table class="table table-hover table-bordered">
				<thead>
					<tr>
						<th>Name</th>
						<th>URL</th>
						<th>Address</th>
						<th>View</th>
						<% if current_user.try(:admin?) %>
							<th>Edit</th>
							<th>Delete</th>
						<% end %>
					</tr>
				</thead>
				<% @universities.each do |university| %>
				<tbody>
					<tr>
						<td><%= university.name %></td>
						<td><%= university.url %></td>
						<td><%= university.address %></td>
						<td>
							<%= button_to :view, university_path(university), 
									options = { 
															method: :get, 
															class: 'btn btn-xs btn-info', 
																type: 'button' 
														} %>
						</td>
						<% if current_user.try(:admin?) %>
							<td>
								<%= button_to :edit, edit_university_path(university), 
										options = { 
																method: :get, 
																class: 'btn btn-xs btn-default', 
																style: 'display: inline;', 
																type: 'button' 
															} %>
							</td>
							<td>
								<%= button_to :delete, university_path(university), 
										options = { 
																method: :delete,
																confirm: 'You sure?', 
																class: 'btn btn-xs btn-danger', 
																style: 'display: inline;' 
															} %>
							</td>
						<% end %>
					</tr>
				</tbody>
				<% end %>
			</table>
		</div><!--.table-responsive-->
		<%= button_to :back, root_path, class: 'btn btn-sm' %>
	</div><!--/#content.content.bg-base.section-->
</div><!--/#main.container-->

app/views/universities/new.html.erb
<%= render 'form' %>

app/views/universities/show.html.erb
<div id="main" class="container">
	<div id="content" class="content bg-base section" style="margin-top: -8%;">	
		<div class="ribbon ribbon-highlight">
			<ol class="breadcrumb ribbon-inner">
				<li><%= link_to 'Home', root_path %></li>
				<li class="active" title="Universities">
					<%= link_to 'Universities', universities_path %>
				</li>
				<li>
					<em><%= @university.name %></em>
				</li>
			</ol>
		</div><!--/.ribbon.ribbon-highlight-->
		<div class="table-responsive">
			<table class="table table-hover table-bordered">
				<thead>
					<th>Name</th>
					<th>URL</th>
					<th>Address</th>
					<th>City</th>
					<th>State</th>
					<th>Zip</th>
					<% if current_user.try(:admin?) %>
						<th>Edit</th>
						<th>Delete</th>
					<% end %>
				</thead>
				<tbody>
					<td><%= @university.name %></td>
					<td><%= @university.url %></td>
					<td><%= @university.address %></td>
					<td><%= @university.city %></td>
					<td><%= @university.state %></td>
					<td><%= @university.zip %></td>
					<% if current_user.try(:admin?) %>
						<td>
							<%= button_to :edit, edit_university_path(@university),
									options = {
															method: :get,
															class: 'btn btn-sm btn-default'
														} %>
						</td>
						<td>
							<%= button_to :delete, university_path(@university),
									options = {
															method: :delete,
															confirm: 'You sure?',
															class: 'btn btn-sm btn-danger'
														} %>
						</td>
					<% end %>
				</tbody>
			</table>
		</div><!--/.table-responsive-->
		<div class="row-fluid">
			<%= render 'team_management' %>
		</div>
			<%= button_to :back, universities_path, class: 'btn btn-sm', method: :get %>
	</div><!--/#content.content.bg-base.section-->
</div><!--/#main.container-->