config/routes.rb
Sevendaysports::Application.routes.draw do
  root to: 'static_pages#home', controller: 'static_pages', action: 'home', as: 'root'

  match 'static_pages/contact', to: 'static_pages#contact', as: :contact

  devise_for :users
  # resources :universities
  # resources :events
  resources :articles
  resources :medias
  # resources :teams

  resources :events do
    resources :articles
    resources :medias
  end

  resources :universities do 
    resources :teams 
  end

  resources :teams do
    resources :events
  end

  resources :users do
    resources :medias
  end

  resources :teams do
    resources :medias
  end

  resources :events do
    resources :medias
  end
  
  # match ':controller(/:action(/:id))(.:format)'
end

app/views/layouts/_authenticate.html.erb
<% if user_signed_in? %>
  <li>
  		<%= button_to('Logout', destroy_user_session_path, method: :delete, 
          class: 'btn btn-sm btn-default') %>
  </li>
<% else %>
  <li>
  	<span>
  	<h5 style="margin-top: 14%; padding-right: 5px;">
  		<%= link_to('Login', new_user_session_path) %>
  	-or- 
  	<%= link_to('Register', new_user_registration_path, 
  			class: 'label label-default') %> 
  	</h5>&nbsp;&nbsp;&nbsp;&nbsp;
  </span>
  <br />
  </li>
<% end %>

app/views/layouts/_flash_messages.html.erb
<!-- <div class="container">
  <%# flash.each do |name, msg| %>
    <div class="alert alert-<%#= name == :notice ? "success" : "error" %>  alert-dismissable" >
    	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%#= msg  %>
    </div>
  <%# end %>
 <!--  Rest of content 
</div>  -->

app/views/layouts/_footer.html.erb
<footer id="footer" class="footer-area">

			<div class="footer-top container">
	
				<div class="row">

					<div class="widget col-xs-12 col-sm-4">

						<h4 class="widget-title">Categories</h4>

						<ul class="entries links links-2-cols">
							<li><a href="blog.html">Entertainment</a></li>
							<li><a href="blog.html">Event</a></li>
							<li><a href="blog.html">Technology</a></li>
							<li><a href="blog.html">Social Media</a></li>
							<li><a href="blog.html">Tactical</a></li>
							<li><a href="reviews.html">Notebook</a></li>
							<li><a href="reviews.html">Smartphone</a></li>
							<li><a href="reviews.html">Tablet</a></li>
						</ul>

					</div><!--/.col-3-->

					<div class="clearfix visible-xs"></div>

					<div class="widget col-xs-6 col-sm-2">

						<h4 class="widget-title">Information</h4>

						<ul class="entries links links">
							<li><a href="#">About</a></li>
							<li><a href="#">Contact</a></li>
							<li><a href="#">Advertise </a></li>
							<li><a href="#">Terms &amp; Conditions</a></li>
							<li><a href="#">Privacy</a></li>
						</ul>

					</div><!--/.col-3-->

					<div class="widget col-xs-6 col-sm-2">

						<h4 class="widget-title">Follow Us</h4>

						<ul class="entries links">
							<li><a href="blog.html"><i class="icon-facebook-sign icon-2x"></i> Facebook</a></li>
							<li><a href="blog.html"><i class="icon-twitter-sign icon-2x"></i> Twitter</a></li>
							<li><a href="blog.html"><i class="icon-google-plus-sign icon-2x"></i> Google Plus</a></li>
							<li><a href="blog.html"><i class="icon-linkedin-sign icon-2x"></i> Linkedin</a></li>
						</ul>

					</div><!--/.col-3-->

					<div class="clearfix visible-xs"></div>

					<div class="widget col-xs-12 col-sm-4">

						<h4 class="widget-title">Subscribe</h4>

						<form class="form-horizontal" role="form">
							<div class="form-group">
								<label for="subscribeEmail" class="col-lg-2 control-label">EMAIL</label>
								<div class="col-lg-10">
									<input type="text" class="form-control" id="subscribeEmail" placeholder="Your Email">
								</div>
							</div>
							<div class="form-group">
								<label class="col-lg-2 control-label">RSS</label>
								<div class="col-lg-10">
									<p class="form-control-static">
										<a href=""><i class="icon-rss-sign"></i> Posts</a> &nbsp; &nbsp;
										<a href=""><i class="icon-rss-sign"></i> Comments</a>
									</p>
								</div>
							</div>
						</form>

					</div><!--/.col-3-->

				</div><!--row.-->

			</div>

			<div class="footer-bottom">

				<div class="container aligncenter">

					<p>&copy;<%= Time.new.strftime('%B, %Y') %> by: sevendaysports.com. <i>All Right Reserved.</i> <p>

				</div>

			</div>

		</footer>
		
		<!-- <script src="../vendor/jquery-1.10.1.min.js"></script> -->
		<!--
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
		<script>window.jQuery || document.write('<script src="../vendor/jquery-1.10.1.min.js"><\/script>')</script>
	-->

		<!-- <script src="../vendor/bootstrap/js/bootstrap.min.js"></script> -->

		<!--	<script src="../vendor/prettyPhoto/jquery.prettyPhoto.js"></script> -->


		<!-- <script src="../vendor/jquery.unveil.min.js"></script> -->
		
	<!--	<script src="../js/main.js"></script> -->
</div>
	<!-- Start of StatCounter Code for Default Guide -->
	<script type="text/javascript">
	var sc_project=9484003; 
	var sc_invisible=1; 
	var sc_security="b9126e56"; 
	var scJsHost = (("https:" == document.location.protocol) ?
	"https://secure." : "http://www.");
	document.write("<sc"+"ript type='text/javascript' src='" +
	scJsHost+
	"statcounter.com/counter/counter.js'></"+"script>");
	</script>
	<noscript><div class="statcounter"><a title="click tracking"
	href="http://statcounter.com/" target="_blank"><img
	class="statcounter"
	src="http://c.statcounter.com/9484003/0/b9126e56/1/"
	alt="click tracking"></a></div></noscript>
	<!-- End of StatCounter Code for Default Guide -->
	</body>
</html>

app/views/layouts/_nav.html.erb
<!-- Navbar -->
<h1 class="sr-only">Sevendaysports</h1>
<nav id="header" class="header-navbar" role="navigation">
	<div class="header-navbar-inner container">
		<div id="brand" class="navbar-brand">
			 <h1 class="sr-only">sevendaysports</h1>
				<%= link_to :sevendaysports, root_path, style: 'rel=bookmark' %>
				<!-- to disable lazy loading, remove data-src and data-src-retina -->
				<!-- <img src="../assets/images/dark-logo.png" data-src="../assets/images/dark-logo.png" data-src-retina="../assets/images/logo-retina.png" width="244" height="56" alt=""> -->
				<!--fallback for no javascript browsers-->
				<noscript>
					<%= image_tag("dark-logo.png") %>
				</noscript>
		</div><!-- END ID brand CLASS navbar-brand -->

		<ul class="nav nav-pages hidden-xs">
			<li><a href="#">About</a></li>
			<li><%= link_to 'Contact', contact_path %></li>
			<li><a href="#">Advertise </a></li>
			<li><a href="#">Terms &amp; Conditions</a></li>
			<li><a href="#">Privacy</a></li>
		</ul>

		<ul class="nav nav-icons">
			<li>
				<a href="#" class="btn-icon" data-toggle=".header-navbar-inner" data-toggle-class="search-toggled-in">
					<span class="search-toggled-out-icon glyphicon glyphicon-search"></span>
					<span class="search-toggled-in-icon glyphicon glyphicon-remove"></span>
				</a>
			</li>
		</ul>
		<ul class="nav navbar-nav navbar-collapes pull-right">
			<li><%= link_to 'Home', root_path %></li>
			<li><%= link_to 'Universities', universities_path %></li>
			<li><%= link_to 'Events', events_path %></li>
			<li><%= link_to 'Articles', articles_path %></li>
			<li><%= render 'layouts/authenticate' %></li>
<!--  <li>
				<p class="navbar-text"><%= link_to 'Media', medias_path %></p>
			</li>  -->
		</ul>
	</div><!-- END CLASS header-navbar-inner container -->
</div><!-- END ID header CLASS header-navbar -->
<!-- /Navbar -->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
 	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
<![endif]-->

<!--[if lt IE 8]>
	<%#= stylesheet_link_tag "font-awesome-ie7.min.css", media: "all" %>
<![endif]-->

<!--[if lt IE 7]>   <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>      <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>      <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->

app/views/layouts/_summarize_header.html.erb
		<meta charset="utf-8">
		<title>sevendaysports</title>
		<meta name="description" content="">

		<!-- Mobile Devices Viewport Resset-->
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">
		<meta name="apple-mobile-web-app-capable" content="yes">

		<!-- <link rel="stylesheet" href="../vendor/bootstrap/css/bootstrap.min.css">

		<link rel="stylesheet" href="../vendor/font-awesome/css/font-awesome.min.css"> -->
		<!--[if IE 8]>
			<link rel="stylesheet" href="../vendor/font-awesome/css/font-awesome-ie7.min.css">
		<![endif]-->

		<!-- <link rel="stylesheet" href="../vendor/prettyPhoto/css/prettyPhoto.css"> -->

		<link href='http://fonts.googleapis.com/css?family=Droid+Sans:400,700|Lato:300,400,700,400italic,700italic|Droid+Serif' rel='stylesheet' type='text/css'>

		<!-- base layout styling -->
<!-- 		<link rel="stylesheet" href="../css/base.css">
 -->
		<!-- components styling -->
<!-- 		<link rel="stylesheet" href="../css/components.css">
 -->		
		<!-- template colorschemes -->
<!-- 		<link rel="stylesheet" href="../colorschemes/dark.css">

			<script src="../vendor/modernizr-2.6.2-respond-1.1.0.min.js"></script>
 -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Sevendaysports</title>
	  <%= stylesheet_link_tag    'application', media: 'all' %>
	  <%= javascript_include_tag 'application' %>
	  <%= csrf_meta_tags %>
	  <%= render partial: 'layouts/summarize_header' %>
	</head>
	<body>
		<%= render 'layouts/nav' %>
		<%= render 'layouts/flash_messages' %>
		<%= yield %>
		<%= render 'layouts/footer' %>
	</body>
</html>
		<!-- <script src="https://code.jquery.com/jquery.js"></script> -->